services:
#  backend:
#    image: 'site-sculpt:latest'
#    build:
#      context: .
#    container_name: 'backend'
#    depends_on:
#      - 'postgres'
#    environment:
#      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://site-sculpt-db:5432/site-sculpt-postgres'
#      - 'SPRING_DATASOURCE_USERNAME=root'
#      - 'SPRING_DATASOURCE_PASSWORD=QfHD6qPLkFUU'
#      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=site-sculpt-db'
      - 'POSTGRES_PASSWORD=QfHD6qPLkFUU'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
    external: false
